# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Last name')),
                ('avatar', models.ImageField(blank=True, max_length=5000, null=True, upload_to='')),
                ('mobile', models.CharField(blank=True, max_length=10, verbose_name='Mobile')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(default='', max_length=50, verbose_name='State')),
                ('country', models.CharField(default='', max_length=50, verbose_name='Country')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
